url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "The Finch" # the name of your site, e.g. ACME Corp

exclude:
  - /_posts/template.md
  - /_contributors/template.md
  - /_category/template.md

permalink: /:year/:month/:day/:title:output_ext

collections:
  contributors:
    output: true
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: category
    values:
      layout: category
  - scope:
      path: ""
      type: contributors
    values:
      layout: contributor

plugins:
  - jekyll-feed
  - jekyll-email-protect
